name: base
channels:
  - conda-forge
dependencies:
  - requests
  # Build tools
  - gcc
  # Geo and data packages
  - planetary-computer
  - rasterio
  - matplotlib
  - xarray
  - cartopy
  - folium
  - pyogrio
  - geopandas
  - shapely
  - rioxarray
  - netCDF4
  - scipy
  - pystac
  - pystac-client
  - dask
  - zarr
  - bottleneck
  - numbagg
  - seaborn
  - cfgrib
  # - kerchunk
  - odc-stac
  - odc-geo
  - rio-stac
  - stackstac
  - boto3
  - duckdb
  - arabic_reshaper
  - contextily
  - ibis-framework
  - rich
  - fsspec
  - pandas
  - xarray-spatial
  - datashader
  - xcube-eopf
  - sentinelhub
  - pydap
  - h5netcdf
  - cftime
  - nc-time-axis
  - icechunk
  - pip:
      - obstore
      - tilebench
      - odc
      - json_repair
      - git+https://github.com/fsspec/kerchunk